name: "Data Model Changeset"
description: Proposed data model updates
title: "[Model Update]: "
labels: ["enhancement"]
assignees:
  - kwittmeyer
body:
  - type: markdown
    propertys:
      value: |
        These are the changes to the data model
  - type: input
    id: request_issue
    propertys:
      label: Request Issue
      description: DM Request Issue # linked to this changeset
      placeholder: ex. "#2223"
    validations:
      required: true
  - type: dropdown
    id: action_type
    propertys:
      label: Action
      options:
        - Add
        - Delete
        - Rename
        - Modify
    validations:
      required: true
  - type: dropdown
    id: action_element
    propertys:
      label: Action element
      options:
        - Node
        - Property
        - Enum
        - Link
    validations:
      required: true
  - type: input
    id: orig_node
    propertys:
      label: Original Node
      placeholder: ex. dataset
    validations:
      required: true
  - type: input
    id: node
    propertys:
      label: New Node
      placeholder: ex. dataset
    validations:
      required: false
  - type: input
    id: node_description
    propertys:
        label: Node Description
        placeholder: "ex. Contains metadata related to datasets"
    validations:
        required: false
  - type: textarea
    id: links
    propertys:
      label: Links and Cardinality
      description: |
        Enter values one per line in the format: Child Node:Cardinality
        Possible carinality values are: many-to-many, many-to-one, one-to-many, one-to-one
      placeholder: |
        Ex:
        clinical_trial:many-to-many
        assay:many-to-many
    validations:
      required: false
  - type: input
    id: orig_property
    propertys:
      label: Original Property
      placeholder: ex. dataset_owner
    validations:
      required: false
  - type: input
    id: property
    propertys:
      label: New Property
      placeholder: ex. dataset_owner
    validations:
      required: false
  - type: input
    id: property_description
    propertys:
        label: Property Description
        placeholder: "ex. The data owner and point of contact"
    validations:
        required: false
  - type: dropdown
    id: datatype
    propertys:
      label: Datatype
      options:
        - "null"
        - enum
        - string
        - LDAP
        - url
        - date
        - float
        - integer
        - array
        - array, object
        - array, string
        - ontology
        - system-generated
        - object
    validations:
      required: false
  - type: textarea
    id: enum
    propertys:
      label: Enum Values
      description: |
        Enter values one per line or if modifying existing enums, 
        provide a mapping in the form old_enum:new_enum one per line
      placeholder: |
        Ex:
        RNAseq
        WGS
        WES
        Ex modify:
        RNAseq:mRNA-seq
        WGS:Whole Genome Sequencing
        WES:Whole Exome Sequencing
    validations:
      required: false

 
