name: "Data Model Changeset - add"
description: Proposed data model updates
title: "[Model Update - add]: "
labels: ["DM Changeset - add"]
assignees:
  - kwittmeyer
body:
  - type: markdown
    attributes:
      value: |
        These are the proposed changes to the data model
        
        Multiple requested changes will require submission of multiple changeset requests
        
        Required Fields:
        Request Issue,  Action Element, Node
        | Action | Action Element | Additional Required Fields | Effect |
        |--|--|--|--|
        | Add | Node | Node Node Description, Links and Cardinality, *Properties new properties need to be added each on their own submission | Major |
        | Add | Property | Node, Property, Property Description, Title, Datatype, Enum Values(if applicable) | Limited |
        | Add | Enum Values |  Original Property, Datatype, Enum Values | Limited |
        | Add | Link | Links and Cardinality | Limited |
        
  - type: input
    id: request_issue
    attributes:
      label: Request Issue Number
      description: DM Request Issue '#' linked to this changeset
      placeholder: ex. "#2223"
    validations:
      required: true
  - type: dropdown
    id: action_element
    attributes:
      label: Action element
      multiple: true
      options:
        - Node
        - Property
        - Enum
        - Link
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node
      placeholder: ex. dataset
    validations:
      required: true
  - type: input
    id: node_description
    attributes:
        label: Node Description
        placeholder: "ex. Contains metadata related to datasets"
    validations:
        required: false
  - type: textarea
    id: links
    attributes:
      label: Links and Cardinality
      description: |
        Enter values one per line in the format: Parent Node:Cardinality
        Possible carinality values are: many-to-many, many-to-one, one-to-many, one-to-one
      placeholder: |
        Ex:
        clinical_trial:many-to-many
        assay:many-to-many
    validations:
      required: false
  - type: input
    id: property
    attributes:
      label: Property
      placeholder: ex. dataset_owner
    validations:
      required: false
  - type: input
    id: title
    attributes:
      label: Title
      placeholder: ex. Dataset Owner
    validations:
      required: false
  - type: input
    id: property_description
    attributes:
        label: Property Description
        placeholder: "ex. The data owner and point of contact"
    validations:
        required: false
  - type: dropdown
    id: datatype
    attributes:
      label: Datatype
      options:
        - "null"
        - enum
        - string
        - LDAP
        - url
        - date
        - float
        - integer
        - array
        - array, object
        - array, string
        - ontology
        - object
    validations:
      required: false
  - type: textarea
    id: enum
    attributes:
      label: Enum Values
      description: |
        Enter values one per line or if modifying existing enums, 
        provide a mapping in the form old_enum:new_enum one per line
      placeholder: |
        Ex:
        RNAseq
        WGS
        WES
        Ex modify:
        RNAseq:mRNA-seq
        WGS:Whole Genome Sequencing
        WES:Whole Exome Sequencing
    validations:
      required: false
