name: Data Model Changeset
description: Request changes to the data model
title: ['test'] 
labels: ["enhancement"]
assignees:
  - kwittmeyer
body:
  - type: markdown
    attributes:
      value: |
        These are the changes to the data model
  - type: input
    id: request_issue
    attributes:
      label: Request Issue
      description: DM Request Issue linked to this changeset (use # to bring up issue numbers)
      placeholder: #2223
    validations:
      required: true
 - type: input
   id: orig_entity
   attributes:
     label: Original Entity/Node
     placeholder: ex. dataset
   validations:
     required: true
 - type: input
    id: entity
    attributes:
      label: New Entity/Node
      placeholder: ex. dataset
    validations:
      required: false
 - type: input
   id: orig_attribute
   attributes:
     label: Original Attribute/Field
     placeholder: ex. dataset_owner
   validations:
     required: false
- type: input
    id: attribute
    attributes:
      label: New Attribute/Field
      placeholder: ex. dataset_owner
    validations:
      required: false
  - type: textarea
    id: enum
    attributes:
      label: Enum Values
      description: Enter values one per line
    validations:
      required: false
  - type: dropdown
    id: action
    attributes:
      label: Action
      options:
        - Add
        - Delete
        - Name Change
    validations:
      required: true
 
