name: "Data Model Changeset - Property"
description: Proposed data model updates
title: "[Model Update - Property]: "
labels: ["DM Changeset - Property"]
assignees:
  - kwittmeyer
body:
  - type: markdown
    attributes:
      value: |
        These are the proposed changes to a property of the data model
        
        Multiple requested changes will require submission of multiple changeset requests
        
  - type: input
    id: request_issue
    attributes:
      label: Request Issue Number
      description: DM Request Issue '#' linked to this changeset
      placeholder: ex. "#2223"
    validations:
      required: true
  - type: dropdown
    id: action_type
    attributes:
      label: Action
      options:
        - Add
        - Delete
        - Rename
        - Modify
    validations:
      required: true
  - type: dropdown
    id: is_new_property
    attributes:
      label: Is this property new?
      options:  
        - Existing
        - New
    validations:
        required: true
  - type: input
    id: node
    attributes:
      label: Node
      placeholder: ex. dataset
    validations:
      required: true
  - type: input
    id: property
    attributes:
      label: Property
      placeholder: ex. dataset_owner
    validations:
      required: true
  - type: input
    id: new_property_name
    attributes:
      label: New Property Name
      description: |
        Required: Rename
      placeholder: ex. dataset_owner
    validations:
      required: false
  - type: input
    id: property_description
    attributes:
        label: Property Description
        description: |
            Required: Add
            Allowed: Modify
        placeholder: "ex. The data owner and point of contact"
    validations:
        required: false
  - type: dropdown
    id: datatype
    attributes:
      label: Datatype
      description: |
        Required: Add
        Allowed: Modify
      options:
        - "null"
        - enum
        - string
        - LDAP
        - url
        - date
        - float
        - integer
        - array
        - array, object
        - array, string
        - ontology
        - object
    validations:
      required: false
  - type: textarea
    id: enum
    attributes:
      label: Enum Values
      description: |
        Required (if datatype is enum): Add
        Allowed (if datatype is enum): Delete, Modify
        Enter values one per line to be added or deleted.
        If modifying existing enums, provide a mapping one per line in the form:
        old_enum:new_enum 
      placeholder: |
        Ex Add/Delete:
        RNAseq
        WGS
        WES
        Ex Modify:
        RNAseq:mRNA-seq
        WGS:Whole Genome Sequencing
        WES:Whole Exome Sequencing
    validations:
      required: false
   - type: checkboxes
     id: cat-preferences
     attributes:
       label: What kinds of cats do you like?
       description: You may select more than one.
       options:
        - label: Orange cat (required. Everyone likes orange cats.)
          required: true
        - label: **Black cat**
